name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Setup gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Test
        run: make test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Format code
        uses: Jerome1337/gofmt-action@v1.0.5

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
